### ISSUE TITLE
TMC2130 DUMP_TMC not working properly on RAMPS

### ISSUE THREAD

**Issue by Master92** [KevinOConnor/klipper#1109]
Hello everybody!

Similar to #1106, I get empty responses from my TMC2130 stepper drivers when trying to read the driver registers via the `DUMP_TMC`-command. Strangely, theses empty responses happen only after a succesful (?) read that I only get, when I do a cold start of klipper and the mcu.

I wired it exactly as needed by Marlin and didn't change a thing when switching from a working config of that. (TMC_SDO -> D50, TMC_SDI -> D51, TMC_SCK -> D52, [see the RAMPS 1.4 schematic](https://reprap.org/mediawiki/images/c/ca/Arduinomega1-4connectors.png))

Strange enough the initial configuration via the `printer.cfg` seems to be working correctly.

Below an excerpt of the `klippy.log` starting from the first working command.

```
DUMP_TMC stepper_x
GCONF:          0000f80f
GSTAT:          01ffffff
IOIN:           ffffffff
TSTEP:          fffffc07
XDIRECT:        c17fffff
MSCNT:          ffffffff
MSCURACT:       fffffdf0
CHOPCONF:       f780ffff
DRV_STATUS:     ffffffff
Stats 1984023.9: gcodein=120 mcu: mcu_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=4306 bytes_read=3779 bytes_retransmit=0 bytes_invalid=0 send_seq=175 receive_seq=175 retransmit_seq=0 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=15874112 heater_bed: target=0 temp=21.5 pwm=0.000  print_time=3.064 buffer_time=0.000 print_stall=0 extruder: target=0 temp=21.9 pwm=0.000
Stats 1984024.9: gcodein=120 mcu: mcu_awake=0.000 mcu_task_avg=0.000000 mcu_task_stddev=0.000000 bytes_write=4321 bytes_read=3885 bytes_retransmit=0 bytes_invalid=0 send_seq=177 receive_seq=176 retransmit_seq=0 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=19 stalled_bytes=0 freq=15874206 heater_bed: target=0 temp=21.4 pwm=0.000  print_time=3.064 buffer_time=0.000 print_stall=0 extruder: target=0 temp=21.9 pwm=0.000
Stats 1984025.9: gcodein=120 mcu: mcu_awake=0.094 mcu_task_avg=0.000320 mcu_task_stddev=0.000509 bytes_write=4351 bytes_read=4003 bytes_retransmit=0 bytes_invalid=0 send_seq=179 receive_seq=179 retransmit_seq=0 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=15874305 heater_bed: target=0 temp=21.5 pwm=0.000  print_time=3.064 buffer_time=0.000 print_stall=0 extruder: target=0 temp=21.9 pwm=0.000
Stats 1984026.9: gcodein=125 mcu: mcu_awake=0.094 mcu_task_avg=0.000320 mcu_task_stddev=0.000509 bytes_write=4357 bytes_read=4109 bytes_retransmit=0 bytes_invalid=0 send_seq=180 receive_seq=180 retransmit_seq=0 srtt=0.004 rttvar=0.001 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=15874282 heater_bed: target=0 temp=21.4 pwm=0.000  print_time=3.064 buffer_time=0.000 print_stall=0 extruder: target=0 temp=21.9 pwm=0.000
DUMP_TMC stepper_x
GCONF:          00000000
GSTAT:          00000000
IOIN:           00000000
Stats 1984027.9: gcodein=152 mcu: mcu_awake=0.094 mcu_task_avg=0.000320 mcu_task_stddev=0.000509 bytes_write=4467 bytes_read=4307 bytes_retransmit=0 bytes_invalid=0 send_seq=189 receive_seq=189 retransmit_seq=0 srtt=0.004 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=15874270 heater_bed: target=0 temp=21.5 pwm=0.000  print_time=7.440 buffer_time=0.077 print_stall=0 extruder: target=0 temp=21.9 pwm=0.000
TSTEP:          00000000
XDIRECT:        00000000
MSCNT:          00000000
MSCURACT:       00000000
CHOPCONF:       00000000
DRV_STATUS:     00000000
```

Excerpt of `printer.cfg`:
```
######## TMC2130-SECTION ########
[tmc2130 stepper_x]
cs_pin: ar44
microsteps: 16
interpolate: True
run_current: .700
hold_current: .210
sense_resistor: 0.110
stealthchop_threshold: 300

[tmc2130 stepper_y]
cs_pin: ar42
microsteps: 16
interpolate: True
run_current: .750
hold_current: .210
sense_resistor: 0.110
stealthchop_threshold: 300

[tmc2130 stepper_z]
cs_pin: ar40
microsteps: 16
interpolate: True
run_current: .950
hold_current: .255
sense_resistor: 0.110
stealthchop_threshold: 500

[tmc2130 extruder]
cs_pin: ar58
microsteps: 16
interpolate: True
run_current: .500
hold_current: .255
sense_resistor: 0.110
stealthchop_threshold: 100
```

It would be very nice if someone might have a possible solution for this problem, as I am currently working on some G-Code commands to live-tune the TMC's settings (i.e. stealthchop-threshold or motor currents).

-Nils

**Comment by nopbit** [comment]
Hello,
Do you power the ramps board with USB only? If yes tmc2130 is not working like that, you must power your printer normally with its power supply. I am also using ramps board and i had the exactly same problem like yours. Turning on the PSU was solved my problem. (I assume that your cs_pins are correct)
Regards

**Comment by Master92** [comment]
Hello nopbit, thank you for your answer.
Contrarily to your question I am running my RAMPS solely on the 12V input and even cut the +5V in my USB cable.

I just found out that setting the driver's registers still works, even if the readouts are completely nonsense.

-Nils

**Comment by KevinOConnor** [comment]
We'd really need to see the full Klipper log in order to assist - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

The initial dump, although not all zeros, doesn't look valid either.  Best guess is that the MISO pin isn't wired correctly.  Another thing to try (although unlikely to help) is to try setting an spi_speed=100000 in the tmc2130 section.

-Kevin

**Comment by Lyr3x** [comment]
I setted up klipper yesterday and finished two prints which came out quite good. I just wanted to test the DUMP_TMC command but there is something wrong because nearly all registers are ffffffff
The drivers working without any problems though. The Mainboard is only powered by the 24V PSU, i also removed the +5V line from the USB cable
Attached the log:
[klippy.log](https://github.com/KevinOConnor/klipper/files/2765171/klippy.log)

**Comment by KevinOConnor** [comment]
There are a number of reasons why the registers will reports all zeros, all 0xff, or random values.  Some possible reasons:
1. The MISO pin is not wired correctly to the TMC2130 chips.  This could be due to the wrong pin used on the micro-controller board (eg, the atmega2560 uses MISO pin PB3 - aka ar50), or the wire is broken / disconnected.
2. Klipper does not support "software SPI", so the tmc2130 chips must be routed to the hardware SPI pins on the micro-controller.  Be aware that each micro-controller chip uses different pins for SPI.
3. In order to correctly configure or query the TMC2130, every chip using the shared SPI bus must be configured in Klipper.  If there is a chip on the bus not in the configuration it will adversely impact all other chips.  Either configure the additional chips in Klipper, or use a static_digital_output section and be sure to set the additional chip's CS pins high.
4. Almost all tmc chips are wired so that their digital logic is powered from motor power.  That means that the motor power must be enabled prior to sending commands to the chips.  If the motor power is interrupted for some reason, it will require a Klipper RESTART to ensure that the configuration is resent to the tmc chips.

-Kevin

**Comment by Lyr3x** [comment]
So i checked everything again and also flashed marlin back to check if this is working and it is. The drivers are working flawless in klipper, just the DUMP_TMC is not working.
1. MISO is wired correctly (register read is working fine in marlin)
2. Not using software SPI
3. No unused chip on the board
4. Using USB Cable without power, so the tmc are getting power at the same time as the rest of the system. Even with a fw restart afterwards the DUMP_TMC is not working for me

**Comment by KevinOConnor** [comment]
I am not sure why that would be.  You could try debugging it - for example, completely disconnect the uc1701 display and see if that helps, try disconnecting all but one tmc2130 driver and see if that helps.  Try changing the microsteps setting on a driver and verify that it takes effect (movement no longer goes as far/short as it should).  Also, be aware that Marlin dumps a lot of information that is static - so it's not always clear if marlin is successfully talking with the driver.

-Kevin

**Comment by KevinOConnor** [comment]
Okay, I'll reopen if there is further information.  To the best of my knowledge the current code works correctly.

-Kevin
