### ISSUE TITLE
[Feature request] TMC2130 stall detection on runtime

### ISSUE THREAD

**Issue by bshowket** [KevinOConnor/klipper#1116]
Is there a chance to implement stall detection on run-time to determine if the stepper about to skip a step for Trinamic TMC2130 ? A failure print could be saved by pause > home x and y > resume printing.
That might not be a priority, but it could be useful for big print!

**Comment by supernielsen** [comment]
+1 on this.. :) this is something i could really use as i often have many hours into a print.

**Comment by trevjonez** [comment]
could be a basis for some other really nice features. IE pause button on the LCD responds seemingly instantly rather than much later (especially when using virtual sd card). responding fast to a pause will be needed for good filament sensor support. Power panic state save and restoration even, plus with klipper being on host software you could hook it up to a proper UPS so it would be a very reliable mechanism compared to depending on eeprom and capacitor charge.

And finally you could even add safety features such as auto pausing a print when something crosses a sensor. (ie hands of children, or maybe even my own, not that I have ever ruined a print by trying to touch stuff while the machine is running :( )

I see this feature request is to say we need real time interrupt support with recovery and then TONS of options come up. Might get pretty interesting with multi MCU setups.

**Comment by mocksoul** [comment]
there is experimental branch with support to smart steppers (mechaduino, ustepper, etc.).
with tmc2130 alone and regular steppers this is impossible

**Comment by bshowket** [comment]
I think Marlin has it implemented this auto skip step detection and recovery during printing with tmc2130.

**Comment by supernielsen** [comment]
They have.. :) but it is something that would be great to have on klipper aswell.. I would choose klipper over marlin any day.. :)

**Comment by trevjonez** [comment]
it certainly wouldn't be perfect but like any open loop control system it ends up being optimistic approximation. you can do step loss detection with the 2130 by polling registers given a correct configuration. nothing as nice as an encoder signal not being in range and throwing an interrupt.

**Comment by mocksoul** [comment]
This would be shame to get false-positive signals and stop printing :))
Go closed loop if you absolutely need this.

I guess closed-loop steppers will in trend soon

**Comment by KevinOConnor** [comment]
Klipper doesn't currently support run-time endstop checking.  It's fine if someone wishes to add this and submit a pull request.  It is not something that I personally plan to implement in the short term.

-Kevin

**Comment by supernielsen** [comment]
I Hope someone would make a pull request.. But at the same time i would rather have regular updates and improvements..

So far very impressed by your work Kevin.. :)

**Comment by KevinOConnor** [comment]
I'm going to mark this as inactive.  If someone wishes to implement it, please open a pull request with the support.

-Kevin

**Comment by mental405** [comment]
Where does one start with implementing this?

**Comment by Frix-x** [comment]
Hi, this feature would be very interesting also for me !
I've not looked that much at the code as I just installed it very recently and I'm not so experienced using Python, but if someone wants to have a look at this with me, I'll be happy to help 👍 

BTW, thank you Kevin for your awesome work !

**Comment by th3fallen** [comment]
+5 this would be amazing!
