### ISSUE TITLE
z over extrudion

### ISSUE THREAD

**Issue by sqrtmo** [KevinOConnor/klipper#1231]
Hi all,

yesterday saw that I have an issue with my z. It seems that my prints are higher than
expected. I did the math and set the "step_distance:" properly, so the head is moving as expected when move manually. But when I print a column I have deviation in z.

The column from the picture should be 40mm, but it si 42.2. Seems like it over extrudes in first ~10 mm and after that seems to print correctly. 

I am using pursa like printer with mesh bed levelling.

Attaching picture and log file.

Thanks in advance!

![img_3111](https://user-images.githubusercontent.com/3294483/52548363-f7c9eb00-2dd5-11e9-8a63-239cf1302ce4.jpg)
[klippy.log](https://github.com/KevinOConnor/klipper/files/2850007/klippy.log)

**Comment by BlackStump** [comment]
did you read the bed_mesh example? in particular about fade_end
https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L184
about scaling ?
https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L187

**Comment by sqrtmo** [comment]
Thanks a lot!

Setting fade_end to 0 solves the problem, but what is the actual purpose of fade?

**Comment by KevinOConnor** [comment]
I'm going to close this as it appears the original question was answered.  The purpose of "fade" (as I understand it) is to gradually remove the Z differences as the print height increases.  It's known to cause artefacts if there are significant Z variations in the mesh, however.  That's why it is not enabled by default.

-Kevin
