### ISSUE TITLE
Temperature stability issues

### ISSUE THREAD

**Issue by urish** [KevinOConnor/klipper#1819]
I'm printing with PETG at 235°C, and I'm observing the following: The temperature is pretty stable for few first few minutes of the print, then it starts fluctuating. Here is a screen shot from Octoprint showing the issue:

![2019-07-17 16_51_24-OctoPrint](https://user-images.githubusercontent.com/892318/61381402-b32a0a80-a8b3-11e9-8baf-50826de51a4b.png)

Eventually, for longer prints, they sometimes fail with "Heater extruder not heating at expected rate" (in the case of the graph above, the print failed with this message about 5 minutes after the screen shot was taken).

I've tried the PID calibration for the heater (calibrated for 235°C), but am still seeing this kind of fluctuation. Would appreciate any points on how to further investigate. Here is my klippy log file (the last print there is the one that failed with the heather error):

[klippy.log](https://github.com/KevinOConnor/klipper/files/3402215/klippy.log)

**Comment by cosminr86** [comment]
What main board do you have?

**Comment by urish** [comment]
CR-20 with Creality V2.1 main board:

![image](https://user-images.githubusercontent.com/892318/61387259-7a436300-a8be-11e9-88f1-cec25d833b97.png)

**Comment by urish** [comment]
So far, I compared printing with heated bed and without heated bed, and it seems like the hotend temperature is much more stable when heated bed is off:

![image](https://user-images.githubusercontent.com/892318/61389892-613cb100-a8c2-11e9-80c9-ca72a3eb87f5.png)

Both prints were done without actual filament in the extruder (just to save on plastic)

strangely enough, when I turn both the hotend and heated bed on manually, not during print, it seems to keep the temperature pretty stable:

![image](https://user-images.githubusercontent.com/892318/61390073-c2fd1b00-a8c2-11e9-8046-91dc7a65b9bf.png)

**Comment by stegmanno1** [comment]
Have the same problems here, after some time of printing the temperature suddenly is not stable...
![2019-07-17 19_45_45-Cube  OctoPrint](https://user-images.githubusercontent.com/53016623/61399013-7ec34800-a8cd-11e9-8dbf-468f5fed4cac.png)

Soon after the print cancels with error "Heater extruder not heating at expected rate" and printing stops.
If i manually increase the temperature a little when it beginns to swap, the print continues without a problem...
![2019-07-17 20_03_33-Cube  OctoPrint](https://user-images.githubusercontent.com/53016623/61399245-01e49e00-a8ce-11e9-8001-b4e1ddd01362.png)

**Comment by urish** [comment]
Okay, this is very strange - I took [one of my GCode files](https://github.com/KevinOConnor/klipper/files/3405277/CCR10_PiCam_U_Bracket.gcode.txt), 
 and manually sent the commands from the beginning of the file to the printer:

```
M140 S70
M105
M190 S70
M104 S235
M105
M109 S235
```

The printer heats up and keeps the temperature stable for 10 minutes without a problem:

![image](https://user-images.githubusercontent.com/892318/61437119-026c4b80-a945-11e9-9ef7-5ac71794e349.png)

However, when printing the, temperature starts to fluctuate after 3-4 minutes or so (that's the graph on the right side): 

![image](https://user-images.githubusercontent.com/892318/61437953-f5505c00-a946-11e9-9d2e-23b5222abf39.png)

Finally, after canceling the gcode print, I ran the first experiment again (sending the heather gcode command from the beginning of the file manually), and it seems to be able to keep the temperature stable (graph on the right side):

![image](https://user-images.githubusercontent.com/892318/61438992-52e5a800-a949-11e9-9490-47fb6eb28727.png)


@KevinOConnor I'd love to get some ideas how to further debug this...

**Comment by urish** [comment]
I did another experiment, adding 5 minute wait (`M4 S300`) inside the gcode file, just after the code that sets the heater temperature:

```
;FLAVOR:Marlin
;TIME:1918
;Filament used: 1.29036m
;Layer height: 0.2
;MINX:85.85
;MINY:97.1
;MINZ:0.2
;MAXX:134.15
;MAXY:122.9
;MAXZ:39.9
;Generated with Cura_SteamEngine 4.1.0
M140 S70
M105
M190 S70
M104 S235
M105
M109 S235
G4 S300
M105
M82 ;absolute extrusion mode
...
```

This seems to delay the temperature fluctuations by several minutes: 

![image](https://user-images.githubusercontent.com/892318/61453603-38222c00-a967-11e9-88ba-112239b48943.png)

Later, I tried pausing mid-print and waiting for ~10 minutes to see if the fluctuations stop, but they continue even after pausing (and keeping the heater on, of course):

![image](https://user-images.githubusercontent.com/892318/61454272-1f1a7a80-a969-11e9-8b19-de1d3fb271ef.png)

**Comment by KevinOConnor** [comment]
This looks like line noise on the thermistor wires and/or power supply voltage fluctuations.

To reduce thermistor wire line noise, avoid running the thermistor wires next to the stepper motor and heater wires.  Some people add a capacitor to the thermistors as well.

If the power supply is struggling to keep up, it may help to reduce the power to the heaters - for example, by adding `max_power: 0.3` to the bed_heater section and `max_power: 0.7` to the extruder.

-Kevin

**Comment by Lissanro** [comment]
I had similar issue, it turned out to be hardware problem. Recently I changed nozzle in my extruder and after calibrating PID for extruder for target 220 this is what I was getting when heating the extruder to 190 (30 degrees below target, this made the issue more pronounced):
![Screenshot 2019-07-17 14:31:50](https://user-images.githubusercontent.com/46057271/61384611-7c96c480-a8a0-11e9-965b-48ad802a2dd3.png)
When I tried to use watermark control I was getting this:
![Screenshot 2019-07-17 14:40:31](https://user-images.githubusercontent.com/46057271/61384947-1b232580-a8a1-11e9-9459-93e348fc4e25.png)
In my case the issue turned out to be that ground connection between Maple Mini and RAMPS wasn't good enough - I accidentally discontented one of ground wires and this caused more noise in the thermistors. For me the issue was fixed by improving ground connection (in my case by connecting the wire I accidentally disconnected). But there maybe other reasons why there is too much noise in the thermistors even if ground connection is good especially if thermistor wires are long and unshielded.

**Comment by urish** [comment]
Thanks for all the input!

As far as power supply - I connected it to a multimeter, and it seems like the voltage is fluctuating between 3.95v and 4.2v while printing - this happens both while the temperature is stable and when it start fluctuating. The idle voltage of the printer is 24.2, and then voltage drops to 3.96v when I ask the printer to heat both the nozzle and the bed at the same time. Does this sound like the expected behavior?

**Comment by Lissanro** [comment]
If you have 24V power supply and under load your multimeter shows you as little as 3.95V or 4.2V, then something is very wrong. Perhaps some capacitors failed in your power supply and do not filter switching noise anymore under load - in this case typical multimeter will show low voltage because of high frequency noise, even if real voltage is still sufficiently high to drive heaters. Obviously, so much noise in power supply is not good and is very likely to cause issues.

When voltage is actually low, this is different issue. For example, recently I had a problem with power supply of my printer - normally it was 12V but under load it became 8-9V and my printer was still working but bed could not reach high temperatures to print ABS. There was no high frequency noise in this case - the voltage was really this low. After I replaced power supply everything started to work normally - under load it was almost 12V. I think that 24V power supply under load should maintain voltage within 22V-24V range and high frequency noise should be filtered good enough so you can see 22V-24V under load on your multimeter.

Another possible cause of noise in thermistors is bad ground connection (or lack of it) in power supply. You can check this by switching your multimeter to measure AC voltage and touching power supply's metal case with one probe of your multimeter while the other probe touches nothing or your body - if you notice AC voltage like few volts or more, ground connection of power supply is bad. This actually can cause issues including additional noise in thermistors.

**Comment by urish** [comment]
@Lissarno thanks for your very detailed comment! I just noticed I wrote `3.95` and `4.2` instead of `23.95` and `24.2`, I was probably too tired and frustrated at the time when I wrote this comment. I have edited it now to reflect the actual numbers. Sorry for the confusion!

**Comment by Lissanro** [comment]
My suggestion to check if power supply grounded properly is still relevant. I know from experience that 3D printer with ungrounded power supply may work unpredictably.

You previously mentioned that with bed turned off temperature appears to be more stable and that suggests you have hardware issue. If your power supply is grounded properly then issue is caused by something else but finding exact cause is not always easy so you may want to try some workarounds, for example KevinOConnor already suggested to try to limit max power or add capacitor to the thermistor.

**Comment by urish** [comment]
Thanks for the suggestion, I will try to check the ground of the PSU!

**Comment by urish** [comment]
Update: I have been printing in lower temperatures since (200-220deg), and it seems like the temperature consistency is much better at this range:

![image](https://user-images.githubusercontent.com/892318/61588916-be2eb480-abab-11e9-9790-701ab7e1b51b.png)

I will close this issue, as it seems to be hardware-related rather than something specific to klipper. Thanks for all the help so far!
