### ISSUE TITLE
MCU 'mcu' shutdown: Timer too close

### ISSUE THREAD

**Issue by bioghost** [KevinOConnor/klipper#2010]
Calibration cubes seem to work fine, I was able to print 3 and adjust setting between each print, no problem. But when trying to print anything more complicated, about halfway through, I get nothing but MCU errors. Previously, I would also occasionally get a "MCU 'mcu' shutdown: next soft pwm extends existing pwm", but was able to solve that by changing the part cooling fans cycle_time from 0.1 to 0.2

What I've tried:
- Disabling all plugins
- Printing from Virtual SD
- Adding ferrite choke to USB cable
- Setting a negative nice value for process (-10)
- Putting SBC (ASUS TinkerBoard) away from printer
- Lowering print speed by half

[klippy.log](https://github.com/KevinOConnor/klipper/files/3649605/klippy.log)

**Comment by KevinOConnor** [comment]
The connection between the host and micro-controller is not stable.  The log indicates the round-trip-time (srtt) is hitting peaks over 50ms.  This could be due to an unusual hardware setup, line noise on the usb cable, voltage issues causing usb interference, host software setup issues (eg, running the host in a container or vm, the host software unable to get sufficient scheduling time), etc.

-Kevin

**Comment by bioghost** [comment]
I'm gonna close this issue because literally nothing fixes the problem and the developer is of absolutely no help
