### ISSUE TITLE
Temperature dependant fan2

### ISSUE THREAD

**Issue by johannes-otto** [KevinOConnor/klipper#21]
Hello,
I configured my printer now. So far everything is pretty straightforward. I love editing the textfile and then just type restart :+1: 

My Printer has a second fan. This fan cools the heatsink of the hotend (the part with the cold filament). It is automatically switched on at 50°C (Marlin). Is there an option to configure this?

Otherwise it would be ok to switch the second fan together with the first one. Do you have an option for that?

**Comment by johannes-otto** [comment]
After some source reading I found out that it's pretty easy to add the temperature fan. Basically I could just derive my fan2 from fan and add the temperature treshold.
What I'm missing is an event to switch the fan2 on. Something like:

if hotend_temp>=fan2.treshold:
  fan2.switch_on()
if hotend_temp > fan2.treshold:
  fan2.switch_off()

**Comment by outlookhazy** [comment]
The current workaround for this is to add a custom command to the mcu section.  
On a couple of occasions I have started writing this feature and then gotten sidetracked by checking out a new branch for some other reason and reverting the change rather than try to merge.  

The logical place would be to have it included in the section for the heater, as that's where the temperature control loop is being evaluated. At the top, you'd check for whether a fan pin is declared, optionally declare/add that as an additional pwm/digital out, and then shoehorn that into the heater temperature control loop with an additional threshold check. I.E. If extruder >=50, enable transition cooler

Eventually it will annoy me enough to try fixing again (24/7 fan using mcu command option - ugh), but python isn't my thing so every attempt has looked kludgy.

**Comment by KevinOConnor** [comment]
On Mon, Jun 26, 2017 at 05:05:30AM -0700, Johannes Otto wrote:
> After some source reading I found out that it's pretty easy to add the temperature fan. Basically I could just derive my fan2 from fan and add the temperature treshold.
> What I'm missing is an event to switch the fan2 on. Something like:
> 
> if hotend_temp>=fan2.treshold:
>   fan2.switch_on()
> if hotend_temp > fan2.treshold:
>   fan2.switch_off()

As a general idea, one could:

* create a new PrinterCoolingFan class derived from PrinterFan
* update fan.py:add_printer_objects() to create a cooling fan for any
  config section starting with "cooling_fan".
* lookup an extruder class in PrinterCoolingFan.__init__() using
  printer.objects.get(extruder_name)
* register a 5 second periodic callback using
  printer.reactor.register_timer()
* check self.extruder.get_temp() from the timer and call
  self.set_speed() accordingly.

-Kevin

**Comment by johannes-otto** [comment]
Thanks,
I will try to implement it this week and then issue a pull request.

**Comment by johannes-otto** [comment]
A more or less stupid question: what unit is the timer? I implemented it, but get strange behavior.

Do you want me to implement it for n-extruder-fans?

**Comment by KevinOConnor** [comment]
On Mon, Jun 26, 2017 at 12:11:11PM -0700, Johannes Otto wrote:
> A more or less stupid question: what unit is the timer? I implemented it, but get strange behavior.

The reactor uses absolute system times represented as seconds since
the system boot time.  A good example is serialhdl.py:_status_event().
Basically, one calls reactor.register_timer(mycallback, reactor.NOW)
and then mycallback() always ends with: return eventtime + 1.0

> Do you want me to implement it for n-extruder-fans?

I'd find every config section starting with a common prefix (eg,
"extra_fan").  It looks like that would need a new wrapper to
klippy.py:ConfigWrapper - something that does: [section for section in
printer.fileconfig.sections() if section.startswith(prefix)]

-Kevin

**Comment by KevinOConnor** [comment]
I've merged in code to support "heater_fan" sections in the config file.

**Comment by outlookhazy** [comment]
Just got around to merging this and it seems to work perfectly, thank you! No more 24/7 fan noise!
