### ISSUE TITLE
Printer not ready

### ISSUE THREAD

**Issue by RaoulFabisch** [KevinOConnor/klipper#2562]
Hi,

I am getting the printer not ready error and don't know how to find out the reason. maybe you can find out in the log.

I am running klipper on an Ender 3 and now switched to silent board and wanted to reflash klipper. now I can't connect anymore

[klippy.log](https://github.com/KevinOConnor/klipper/files/4250649/klippy.log)

**Comment by StrikeEagleCC** [comment]
Did you happen to change the baud rate when you did `make menuconfig`? Have you verified your serial port is correct?

**Comment by KevinOConnor** [comment]
Typically these types of connection issues are due to an incorrect configuration during "make menuconfig", or an unsuccessful flash.  My best advice is to rerun "make menuconfig", be sure to leave the "low-level configuration options" not selected, double check the values that are used, and then reflash the board.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this ticket as it looks like the conversation has concluded.

-Kevin
