### ISSUE TITLE
 Move out of range

### ISSUE THREAD

**Issue by normsteel** [KevinOConnor/klipper#2588]
Hi, 

Getting a error saying Move out of range: 5.602 24.308 -1.005 [0.000] when I try and start a print after levelling the bed. 
[klippy.log](https://github.com/KevinOConnor/klipper/files/4290969/klippy.log)
[printer_cfg.txt](https://github.com/KevinOConnor/klipper/files/4290979/printer_cfg.txt)

**Comment by ld3300** [comment]
Hi @normsteel 

Your bed is pretty out of level, you may want to level it a bit more before probing with the BL touch, you have more than a 2mm difference in height from one corner to the opposite. The real issue is that your stepper_z position_min is set to -0.99, so when your nozzle tried to go somewhere near your low corner (which is at -1.408mm) it hit the limit you gave it and stopped the print.  You can make your z limit a lower number (further negative), but doing a little leveling will probably make your life easier.

In the future please include the entire log file.  It makes helping a lot easier.

-David
