### ISSUE TITLE
QUAD_GANTRY_LEVEL  report errors

### ISSUE THREAD

**Issue by zouzheng2526** [KevinOConnor/klipper#2656]
Sometimes when I execute the quad gantry level command,report errors:
"Your printer's firmware reported an error. Due to that the ongoing print job will be cancelled. Reported error: Retries aborting: Probed points range is increasing. Possibly Z motor numbering is wrong."
I don't know where the problem is and how to fix it.
Please help,Thank you.
[klippy.log](https://github.com/KevinOConnor/klipper/files/4400609/klippy.log)

**Comment by FHeilmann** [comment]
after each run of QGL, QGL adjusts your steppers and reports a 'max error'. This error should decrease until it reaches below the retry_tolerance you have set.

If your belt locations are incorrect or your z motors are missing steps, at some point the max error will start increasing instead of decreasing. That's when the error occurs.

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin
