### ISSUE TITLE
TMC2208/TMC2209 hardware UART

### ISSUE THREAD

**Issue by leptun** [KevinOConnor/klipper#3136]
I'm not sure if it's a mistake I'm making or it's just a missing feature, but in any case I have issues trying to connect TMC2209 drivers to a MiniRambo board. The way I have the drivers connected is by using the UART2 lines in the configuration that also works for marlin (with the resistor).
The issue I'm having now is that I can't actually use the hardware UART unit that is found in the atmega2560. Instead, it seems that Klipper wants to use the pin change interrupt function and not the actual hardware. Those hardware uart pins don't have PCINT support, so I'd have to swap around quite a lot of pins to get everything working just like it did with my modded Prusa-Firmware.

Here is the error I get when trying to "restart the firmware":
```
Send: status
Recv: // Unable to read tmc uart 'stepper_x' register IFCNT
Recv: // Once the underlying issue is corrected, use the "RESTART"
Recv: // command to reload the config and restart the host software.
Recv: // Printer is halted
Recv: // Klipper state: Not ready
Recv: !! Unable to read tmc uart 'stepper_x' register IFCNT
Recv: ok
```

[klippy.log](https://github.com/KevinOConnor/klipper/files/5000911/klippy.log)
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/5000912/printer.cfg.txt)
[pins_TMC2209_MAP.txt](https://github.com/KevinOConnor/klipper/files/5000920/pins_TMC2209_MAP.txt)

**Comment by KevinOConnor** [comment]
Klipper never uses "gpio hardware irqs" - see: https://www.klipper3d.org/FAQ.html#do-i-have-to-wire-my-device-to-a-specific-type-of-micro-controller-pin

Klipper can use any regular gpio pin for the uart wire.  Only one wire is needed (although you can also define both rx and tx if you wish).

An "Unable to read tmc uart 'stepper_x' register IFCNT" error indicates Klipper was unable to communicate with the given driver.  Make sure the driver has motor power when starting Klipper.  Otherwise, triple check the pins.  If unsure, just define the one uart_pin.

-Kevin

**Comment by KevinOConnor** [comment]
I'm going to close this as it looks like the conversation has concluded.

-Kevin
