### ISSUE TITLE
Z_Tilt_Adjust

### ISSUE THREAD

**Issue by Hairyloon** [KevinOConnor/klipper#3222]
When I run Z_Tilt_adjust, it always adjusts both motors, where I would expect that if it is adjusting the tilt then it would only need to move one. Is there some good reason for this that I cannot spot?
Also, if I run it again, I would expect it to not need any adjustment the second time and it invariably does, usually, it seems by the opposite adjustment to the last one.
Obviously there is some error margin in the probe which might account for it, it was just a bit of a puzzle.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5108632/klippy.log)

**Comment by KevinOConnor** [comment]
> When I run Z_Tilt_adjust, it always adjusts both motors, where I would expect that if it is adjusting the tilt then it would only need to move one. Is there some good reason for this that I cannot spot?

If there are only two motors defined, then only one is actually moved.  The second will be "virtually moved" by changing the coordinate system so as to make the measurements match the probe's z_offset.

> Also, if I run it again, I would expect it to not need any adjustment the second time and it invariably does, usually, it seems by the opposite adjustment to the last one.

This is generally due to slight errors in the configured motor position and/or configured probe x/y/z offsets.  The normal practice is to configure the z_tilt `retries` parameter so that a flat bed is obtained even with slight errors in the configured positions.

-Kevin

**Comment by Hairyloon** [comment]
Thank you.
I think that covers it so I'll close this, although I have the nagging feeling that there was something else that I'm forgetting.
