### ISSUE TITLE
MCU 'mcu' shutdown: Timer too close

### ISSUE THREAD

**Issue by 50koruny** [KevinOConnor/klipper#3551]
Hi.
 have failed a very long print (40 hours) with a lot of polygons.

![IMG_20201119_115639085](https://user-images.githubusercontent.com/49877841/99657537-90d36e80-2a5e-11eb-8463-e23d23820380.jpg)
.

Can you, help me with that, please?
I dont have an idea why did it happen.
Have searched here (lot of "timer too close" issues), but there is more reasons why it can happen, i am a little bit lost in this.

Raspberry 3B+ and Anycubic Kossel Linear Plus.
Thank you very much.
[klippy.log](https://github.com/KevinOConnor/klipper/files/5566231/klippy.log)

**Comment by KevinOConnor** [comment]
Unfortunately, it looks like some kind of system event occurred on the host Raspberry Pi which led to the failure.  Specifically, the Klipper thread that manages the PID heater didn't get any processing time for over 1.5 seconds.

It's not clear what the "system event" was or its root cause.  If you're familiar with Linux, you could look through the system logs to see if there is an error report at the time of the failure (eg, overheating, undervoltage, sd card error, out of memory, or similar).

-Kevin
