### ISSUE TITLE
Klipper Cannot reconnect after drv8825 failure

### ISSUE THREAD

**Issue by ejg3855** [KevinOConnor/klipper#439]
DRV8825 decided to blow the magic smoke and some flames ( I stopped it instantly). 

Pulled the power to the ramps/mega setup. 

I replaced the drv8825 and am trying to reconnect, but cant get past:

Recv: // Printer is not ready
Recv: // The klippy host software is attempting to connect.  Please
Recv: // retry in a few moments.
Recv: !! Printer is not ready

[klippy.log](https://github.com/KevinOConnor/klipper/files/2147315/klippy.log)

**Comment by AxMod3DPrint** [comment]
It just can't find the port, which suggests the port changed, possibly from
ttyACM0 to ttyACM1, you can check this by using `ls -al /dev/ttyA*` on the
Pi. If no port has been listed, it could be that the driver took out the
Arduino when it nuked itself.

**Comment by hg42** [comment]
even without finding the port, there should be a log file.

How do you start klippy?
If you do this manually (not using the provided script) then you need to add an option for the log file to the command line.

**Comment by ysoldak** [comment]
I had the same problem yesterday, the system assigns first free USB port, and sometimes it becomes /dev/ttyACM1 instead of expected /dev/ACM0, and that's irritating.

Found a solution on the internets today, have to try later, but feel free to try also and tell if works for you.

Run
`ls -l /dev/serial/by-id/`

Shall return something like
`lrwxrwxrwx 1 root root 13 Mar 4 06:37 usb-1a86_USB2.0-Serial-if00-port0 -> ../../ttyUSB0`

So we need "usb-1a86_USB2.0-Serial-if00-port0"
and in `printer.cfg` we put
```
...
[mcu]
serial: usb-1a86_USB2.0-Serial-if00-port0
...
```

**Comment by hg42** [comment]
https://github.com/KevinOConnor/klipper/blob/2c4ca8888784dc9af1d917df33193b6c35196761/docs/FAQ.md#wheres-my-serial-port

**Comment by ejg3855** [comment]
When I run 
`ls -1 /dev/serial/by-id/`

it returns
`ls: cannit access '/dev/serial/by-id/': No such file or directory`

**Comment by AxMod3DPrint** [comment]
That would suggest your Arduino is fried as it's not creating the port.
Creating the tty ports is not dependent on Klipper, it's within the Linux
system kernel. If no port is created, then it's most likely that the FTDI
chip or Voltage regulator has been fried due to a back surge when the
Driver nuked itself

'Eagles may soar, but Weasels don't get sucked into Jet engines'
