### ISSUE TITLE
‘i2c_config’ has incomplete type      struct i2c_config i2c_config;

### ISSUE THREAD

**Issue by outbackdingo** [KevinOConnor/klipper#4409]
Compiling out/src/i2ccmds.o
src/i2ccmds.c:14:23: error: field ‘i2c_config’ has incomplete type
     struct i2c_config i2c_config;

**Comment by TheFanatr** [comment]
Why did you close this? I have the same problem; did you find a solution or is this effect due to misuse? If it is the latter, could you please share what you did differently to make it work? Was going to open an issue myself.

**Comment by outbackdingo** [comment]
make clean && git pull && make menuconfig again... worked for me.

**Comment by TheFanatr** [comment]
I just PR'd it so that people know what to do until someone fixes the `menuconfig` script.

**Comment by TheFanatr** [comment]
@KevinOConnor I disagree that this is invalid, because the instructions in the installation documentation are incomplete, and as a direct result a lot of beginners have this same issue until they read the comments of #3682 or happen to read the "How to Upgrade" section of the FAQ which has users perform the step described in the aforementioned comments. I should also note that the answer (mentioned in all of the places noted previously), provided by @outbackdingo, is a sufficient workaround but this does not make the issue fixed, or make it not an issue, or instead make a help request; every user who does not perform a `make clean` in between `make menuconfig` and `make` will have the build fail on them, yet this is exactly what the documentation tells them to do in a vary obvious and visible place. I ask that you reconsider this decision.

**Comment by redfox05** [comment]
Just to note, I also came across this during a fresh install on octopi Raspberry Pi 3, which crashed during the `make` command. Running the clean instructions above allowed things to continue as normal.

**Comment by trek-e** [comment]
Still an issue, just ran into this on my RPI 3 as of Jan 1 2022.

**Comment by MattEvansA45** [comment]
As above, I've just encountered this issue following the steps on the main installation page.
![image](https://user-images.githubusercontent.com/41288088/150779508-4f1e7d1c-08d2-4a5b-9244-8f1f7046fe2e.png)

**Comment by TheDopple** [comment]
FWIW, this worked for me:
![image](https://user-images.githubusercontent.com/8251269/166125334-79450609-2182-4301-93f0-10a3ff2d25b3.png)

**Comment by rsilvers129** [comment]
Had this issue today so it is still not fixed.
