### ISSUE TITLE
SKR E3 Turbo Config - Missing GPIO pin information

### ISSUE THREAD

**Issue by TheDragonlizard** [KevinOConnor/klipper#4421]
Following some of the steps in this issue https://github.com/KevinOConnor/klipper/issues/3549 I was finally able to get my turbo working again, however only adding the standby pins to printer.cfg was inneffective, and I needed to add them to GPIO pins in make menuconfig. The config or instructions currently lack any information on this. A simple 
#####GPIO pins to be added in Menuconfig !P3.26, !P3.25, !P1.18, !P1.19 #####
at the top of the config would be super helpful and would at least have saved me a lot of time.

**Comment by Majestry** [comment]
That's quite strange - i use E3 turbo on my ender3v2 with all pins set in printer.cfg (btw, there are 5 pins, because of 5 drivers) and had nothing to change in menuconfig.  Here is my section from printer.cfg
`[static_digital_output tmc_standby_pins]` 
`pins: !P3.26, !P3.25, !P1.18, !P1.19, !P2.13`
