### ISSUE TITLE
Pins name great than ar69

### ISSUE THREAD

**Issue by nightdemonx** [KevinOConnor/klipper#548]
The new board F6 (https://github.com/FYSETC/F6) have pins great than 69. If i set pin for example ar74 i have this error:
Send: status
Recv: // Unable to translate pin name: config_spi oid=2 bus=0 pin=ar74 mode=3 rate=4000000 shutdown_msg=
Recv: // Once the underlying issue is corrected, use the "RESTART"
Recv: // command to reload the config and restart the host software.
Recv: // Printer is haltedRecv: !! Unable to translate pin name: config_spi oid=2 bus=0 pin=ar74 mode=3 rate=4000000 shutdown_msg=Recv: ok

**Comment by KevinOConnor** [comment]
You need to attach the klipper log file in order for us to assist.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by nightdemonx** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2300435/klippy.log)
Added log file.
Thank you.

**Comment by KevinOConnor** [comment]
The arduino pin mapping enables the pin aliases defined on real Arduino boards.  There is no "Arduino D74" pin on the Arduino Mega - someone invented "74" for one of the additional pins found on the atmega2560 that aren't on the Arduino Mega.

To access the desired pin in Klipper, use the actual hardware name (eg, "PJ7" instead of "ar74").

Indeed, given how confusing the arduino pin aliases are, I recommend using the actual hardware pin names whenever possible.

-Kevin

**Comment by KevinOConnor** [comment]
FYI - a FAQ section was recently added on this.  See: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#how-do-i-convert-a-marlin-pin-number-to-a-klipper-pin-name

**Comment by Hywelmartin** [comment]
late to the party @KevinOConnor ....

Are there any other benefits to convert from arduino pins to hardware dito?.. in case a conversion in the docs might be good..
