### ISSUE TITLE
Movement Error at Beginning of Print with Mesh Leveling Configured

### ISSUE THREAD

**Issue by rothnic** [KevinOConnor/klipper#626]
**Pre-Conditions:** 
* I configured manual mesh leveling, so I'm in the back right corner of the bed. Note, I have to actually adjust the z position of some points for the problem to occur
* I execute a G28 as part of my print to test out the leveling, which takes me back to the front left corner
* I issue `G1 Z15.0 F3000` to move the bed down some before beginning the print.

**Expected:**
* The bed should move straight down before proceeding to any horizontal movement.

**What Happens Instead:**
* The printer makes a direct move in X, Y and Z at the same time to the original location that I was at, at the end of the grid configuration (Coordinates are ~[310, 310, 10]), usually hitting the corner of my bed clips in the process
* Immediately after reaching the original location, the printer moves to [0, 0, 15], where I wanted it to go to from the start

**Other Notes:**
* This also occurs after each print where mesh leveling is enabled, because at the end of each print my end gcode parks the extruder in the back right so it is out of the way. The issue might not be noticed by others if they go back to home at the end of their prints.
* I worked through running the commands manually to eliminate other factors, rather than going into a print and it is still occurs when I simply do: (manual mesh leveling where I adjust z position, `G28`, `G1 Z15.0 F3000`)
* After the initial travel to the back right point after homing, then ending up at [0, 0, 15], I can run the same command afterwards and it works as expected
* Resetting Klipper, which clears the mesh leveling config, results in the issue no longer occurring, until I configure the mesh leveling again

**Additional Info:**
Printer: TronXY x5s (stock board)
Klipper Host: Raspberry Pi 3
Error Log: [klippy_grid_position_error.log.zip](https://github.com/KevinOConnor/klipper/files/2364066/klippy_grid_position_error.log.zip)

**Comment by Arksine** [comment]
So what I believe is happening here is that the cached previous position in bed_mesh.py is becoming stale because you execute a G28 after mesh leveling.  I'm not sure why this would happen after a print, unless you are rehoming or otherwise moving the tool outside of normal gcode commands.


@KevinOConnor Perhaps I should go back to fetching the previous position by calling get_position(), rather than cache it in bed_mesh?  Any direct calls to toolhead.move() after the mesh has been applied will result in a stale cached position.

**Comment by theopensourcerer** [comment]
That could make sense. I have a macro button in Octoprint which does

G28
MESH_BED_CALIBRATION
G28

**Comment by rothnic** [comment]
I ran some more prints to do some unrelated tuning and added a G28 at the end, to hopefully work around the issue. However, it still resulted in moving directly to the last position of the print, before I executed the G28. So I guess if I had moved via 'g1 X0 Y0' at the end, it might have worked around the issue.

What i don't understand is why the previous position would be relevant at all after a g28.

**Comment by KevinOConnor** [comment]
@Arksine - if caching the last_position, then it must be reset on a get_position() call.  (Specifically, gcode.py:reset_last_position() is called any time the head is moved outside of a gcode command, and reset_last_position() will always call transform.get_position().)

-Kevin

**Comment by Arksine** [comment]
Thanks Kevin. I'll make that fix and submit a PR for it.

@rothnic The last position is relevant because bed_mesh has to traverse a move.  It splits moves into smaller sections whenever a z-adjustment has to be made.  So when G28 is executed, bed_mesh thinks the last move is where the tool was prior to homing.  Then it detects a split, which moves the toolhead back near the position prior to homing.  I should have a fix shortly.

**Comment by rothnic** [comment]
I updated and tried it again and it looks to be fixed. Thanks @Arksine.
