### ISSUE TITLE
Bl touch repetability test

### ISSUE THREAD

**Issue by Thesecky** [KevinOConnor/klipper#747]
Marlin has a repetability test for the bl touch. Does klipper have anything similar and if not, what comands can i use to calculate it myself.

**Comment by derdigge** [comment]
@Thesecky 

I use a macro for it. Not the same but you can get an idea how ecxact your probe is. Just move your probe to desired position and issue a M48.

`[gcode_macro M48]
gcode:
	G1 Z5
	PROBE
	G1 Z5
	PROBE
	G1 Z5
	PROBE
	G1 Z5
	PROBE
	G1 Z5
	PROBE
	G1 Z20`

**Comment by Thesecky** [comment]
This is what i get.
![image](https://user-images.githubusercontent.com/34596070/46906659-44c0b200-cf07-11e8-9bf7-0e8dc77884dd.png)
Are those results supposed to be that good, i would expect at least some difference between the measurments.

**Comment by derdigge** [comment]
It looks to good to be true. Maybe our bltouch is a special ninja one? 👍 
What about increasing probe speed and see whats then?

**Comment by KevinOConnor** [comment]
FYI, the inductive probe on my delta printer gets the same results when I probe the same spot.  The probe should be returning identical results.

-Kevin

**Comment by derdigge** [comment]
@KevinOConnor Sorry for spaming. Which probe do you use at what probe speed?

**Comment by KevinOConnor** [comment]
It's a pretty standard 12V inductive probe.  I don't have the part number handy, but it looks like https://reprap.org/mediawiki/images/thumb/2/23/Inductive-sensor-blue.jpg/300px-Inductive-sensor-blue.jpg

To be clear, this probe isn't useful on my delta printer - I get different readings at different parts of the bed because minor differences in arm length result in a tilt to the effector.  That said, if I probe the same location multiple times in a row I generally get the same exact reading from the inductive probe.

I use the default probing speed of 5mm/s.

-Kevin

**Comment by derdigge** [comment]
Thanks. I use the same in a 24v system. So the probe is powered with 24v. But i have small fluctuation in the probings ~ 0.01 - 0.04. I probe with 2mm/s. Do you power it with 12v? Maybe i should try it

**Comment by KevinOConnor** [comment]
Yes - 12V.  It's not unusual for me to see one step difference, but it's pretty stable for me.  I just ran a quick test (my step distance is .0125 so the difference below is just one step):
```
Recv: // probe at -2.028,-2.138 is z=0.370724
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.370724
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.358224
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.370724
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.370724
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.370724
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.358224
Send: G1 Z2
Recv: // probe at -2.028,-2.138 is z=0.370724
```
