### ISSUE TITLE
pressure advance

### ISSUE THREAD

**Issue by beyondzvincent** [KevinOConnor/klipper#776]
i just followed the pressure advance.md to config my printer, it works and got a value of 0.18, after that i put that on klipper config file and restart the firmware, but did not work this time, i tried again to print the square.stl, i found out that it did not to any pressure advance until i manual issue a SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=0 ACCEL=500 in gcode, please advice.

**Comment by KevinOConnor** [comment]
In general, you need to update the config file with the final pressure advance setting - see the text "At the completion of this test, update the extruder's pressure_advance setting in the configuration file and issue a RESTART command. The RESTART command will also return the acceleration and cornering speeds to their normal values." at: https://github.com/KevinOConnor/klipper/blob/master/docs/Pressure_Advance.md

Otherwise, you'll need to attach the klipper log file in order for us to assist further - see: https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by beyondzvincent** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/2476680/klippy.log)
Hi, here is my klippy.log, please have a look

**Comment by KevinOConnor** [comment]
That log indicates Klipper is configured with pressure_advance=0.20 - everything in the log appears normal.

-Kevin

**Comment by beyondzvincent** [comment]
yes, and as i said, when i try to print the square.stl again, the extruder doesnt have the pressure advance like movement until i manual issue SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=0 ACCEL=500 in terminal, any idea?

**Comment by KevinOConnor** [comment]
Pressure advance isn't impacted by that command.  What you're likely seeing is that the printer's max_accel value is too high to accomplish the desired pressure advance.  This is described in the "Important Notes" section of the pressure advance tuning guide - https://github.com/KevinOConnor/klipper/blob/master/docs/Pressure_Advance.md#important-notes

An acceleration of 4000 is quite high.  Try lowering it (eg, 2000).  It shouldn't be necessary to tune square_corner_velocity (you can leave it at the default of 5).

-Kevin

**Comment by beyondzvincent** [comment]
Thanks for advice, let me try
