### ISSUE TITLE
Temperature not remaining stable for a few seconds

### ISSUE THREAD

**Issue by dushyantahuja** [KevinOConnor/klipper#842]
Please see attached log and screenshot from Octoprint. The temperature goes down to almost 5 degrees below setpoint while printing. It stays stable most of the time - but there are dips.
[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/2537787/klippy.log.zip)
<img width="592" alt="screenshot 2018-11-01 at 08 25 23" src="https://user-images.githubusercontent.com/6416649/47841545-dd817980-ddb1-11e8-8724-4a7aff93b100.png">

Not sure why this is happening - had never seen this when I was running smoothieware. The board is a cohesion 3D ReMix (http://cohesion3d.com/cohesion3d-remix/) with an e3D Titan.

**Comment by manu7irl** [comment]
> Please see attached log and screenshot from Octoprint. The temperature goes down to almost 5 degrees below setpoint while printing. It stays stable most of the time - but there are dips.
> [klippy.log.zip](https://github.com/KevinOConnor/klipper/files/2537787/klippy.log.zip)
> <img alt="screenshot 2018-11-01 at 08 25 23" width="592" src="https://user-images.githubusercontent.com/6416649/47841545-dd817980-ddb1-11e8-8724-4a7aff93b100.png">
> 
> Not sure why this is happening - had never seen this when I was running smoothieware. The board is a cohesion 3D ReMix (http://cohesion3d.com/cohesion3d-remix/) with an e3D Titan.

did you try PID calibration?

`Calibrate PID settings
Klipper supports PID control for the extruder and bed heaters. In order to use this control mechanism it is necessary to calibrate the PID settings on each printer. (PID settings found in other firmwares or in the example configuration files often work poorly.)

To calibrate the extruder, navigate to the OctoPrint terminal tab and run the PID_CALIBRATE command. For example: PID_CALIBRATE HEATER=extruder TARGET=170

At the completion of the tuning test run SAVE_CONFIG to update the printer.cfg file the new PID settings.

If the printer has a heated bed and it supports being driven by PWM (Pulse Width Modulation) then it is recommended to use PID control for the bed. (When the bed heater is controlled using the PID algorithm it may turn on and off ten times a second, which may not be suitable for heaters using a mechanical switch.) A typical bed PID calibration command is: PID_CALIBRATE HEATER=heater_bed TARGET=60`

**Comment by dushyantahuja** [comment]
Yes. As you can see from the screenshot, the temperature is stable for most
of the print, except for sudden dips.

**Comment by BlackStump** [comment]
have you tried a new extruder heater? ....I have experienced this before that a replacement heater fixed .
I initially thought it was a poor connection/ broken wire but because it was intermittent it was difficult to pin down ....so went the sledge hammer approach of just replacing heater. I doubt it is a firmware issue.

**Comment by james-golden** [comment]
One problem that I had with mine was a loose thermistor in the heater block.  I would get problems like not heating quick enough and some times some good dips in the temps and some times the heat would jump up several degrees also.  I now put the thermistor in as far as I can and then add a dab of high temp RTV.  I works pretty well and I have had no problems since doing this.  Don't fill the whole thermistor hole with the rtv, if you do, you might need a new heater block.  Been there and done that.

**Comment by KevinOConnor** [comment]
@dushyantahuja - it does look like Klipper could have done better.  Prior to the dips Klipper turns off the heater for a few seconds, and then it needs to turn the heater full on for many seconds to recover.  This looks like it is due to the extremely noisy adc sensor on the lpc176x chips.  (As a guess, a severe noise event results in a distortion of the temperature slope measurement, which results in an undesirable amplification of the Kd parameter.)

Increasing the heaters's smooth_time may help.  A code change to use a "median filter" in Klipper may ultimately be necessary, however.

-Kevin

**Comment by klHaribo** [comment]
I had the same problem.
changing heater and thermistor solved it for me.

**Comment by BlackStump** [comment]
https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L959

**Comment by BlackStump** [comment]
the run of the mill chinese thermistor if that is what you are looking for
sensor_type : NTC 100K beta 3950
that info is in the example.cfg
https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L152

**Comment by gabi0110** [comment]
@BlackStump thank you for answer but i don't think that's the same thermistor. In fact they don't look the same and I don't know if they have the same temperature ramp.

**Comment by KevinOConnor** [comment]
FYI, I created a development branch that implements a median filter on temperature reports.  I think this should fix the issue with noise on the smoothieboards.  To test the branch:

cd ~/klipper ; git fetch ; git checkout origin/work-median-filter-20190104 ; sudo service klipper restart

and update the smooth_time parameter in printer.cfg to a value of 2.7 (see the updated config/generic-smoothieboard.cfg for further details).

Let me know of your results.
-Kevin

**Comment by KevinOConnor** [comment]
The latest mainline code now implements a median filter in the lpc176x micro-controller code (commit d3ec1038).  It is currently believed that this additional feature will resolve the problems raised in this issue.

It is recommended that anyone using an lpc176x board upgrade to the latest code, recompile the micro-controller code, and reflash the board.

-Kevin

**Comment by dushyantahuja** [comment]
Thanks a lot - the latest update solves this issue completely. Apologies, I was not able to test earlier. My printer was down as I had managed to break the Z-axis fittings (I'm using a belted Z-axis).

<img width="546" alt="screenshot 2019-01-25 at 23 07 06" src="https://user-images.githubusercontent.com/6416649/51777669-f7530400-20f5-11e9-9ec6-e9a6081ee494.png">

Is this still recommended:

[static_digital_output ground_unused_analog_pins]
pins: !P0.2, !P0.3, !P0.25, !P0.26, !P1.30, !P1.31

?

**Comment by KevinOConnor** [comment]
>Is this still recommended:
[static_digital_output ground_unused_analog_pins]
pins: !P0.2, !P0.3, !P0.25, !P0.26, !P1.30, !P1.31

No - other testers reported that it did not have a substantial impact.  Updating to the latest code (with the median filter) is the only thing needed.

-Kevin
