### ISSUE TITLE
printer is not ready

### ISSUE THREAD

**Issue by Logjm** [KevinOConnor/klipper#859]
I have tried installing klipper a million times and I keep getting the printeer not ready command.  i would appreciate some trouble shooting advice.  Everything seems to be correct looking throught the files in filezilla.

Send: status
Recv: // Printer is not ready
Recv: // The klippy host software is attempting to connect.  Please
Recv: // retry in a few moments.
Recv: // Klipper state: Not ready
Recv: !! Printer is not ready
Recv: ok

Send: M112
Send: N3 M112*34
Send: N4 M104 T0 S0*37
Recv: ok
Send: N5 M140 S0*96
Closing serial port due to emergency stop M112.
Recv: ok
Connection closed, closing down monitor
Changing monitoring state from "Operational" to "Offline (Error: Closing serial port due to emergency stop M112.)"

**Comment by bruce356** [comment]
Hi, if you want someone to help you need to attach your klippy.log file found in the /tmp/ folder.
I know it can be frustrating but once the errors are sorted you will be happy to be using Klipper.
regards - bruce

**Comment by jakep82** [comment]
You need to attach your log file. 

https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

**Comment by Logjm** [comment]
The directions aren't clear enough.  I don't know how to retrieve the log.

**Comment by BlackStump** [comment]
you need to give a little more info on how to better direct you.
are you using Windows OS to run Octoprint?
if so you need WinSCP to retrieve the log file mentioned above from you Rpi of OrangePi or any other linux  based single board computer that you are installing/running Klipper on.
https://winscp.net/eng/index.php
what controller board are you using etc etc?
 have you read and followed the installation instructions? have you looked at the config files that is right for your printer or controller because there can be hints there as well.

**Comment by LazaroFilm** [comment]
To retrieve the klippy log, go into your Pi via FTP (or pull the as card and put it in a card reader) in the root of the card is a folder named tmp and inside should be a file named Klippy.

**Comment by thesleepydog** [comment]
I had this error. I re-flashed the compiled firmware for my MEGA 2560, using UART0 (didn't matter what port on the Pi the Mega is plugged into), and 25000 baud to my arduino mega and it worked
