### ISSUE TITLE
How to Calibrate Steps ?

### ISSUE THREAD

**Issue by xsasx** [KevinOConnor/klipper#934]
How do i calibrate my steps with klipper - in marlin it was easy and many tutorials are around - but how it goes with klipper `?

**Comment by theopensourcerer** [comment]
Do the same calibration as with ANY printer and then divide the result by 1 to get mm/step rather steps/mm.

**Comment by xsasx** [comment]
ok - and where i put my result in ?

**Comment by theopensourcerer** [comment]
Err, look at the example configuration files. They will show you all the options and are well commented. You need to set the step_distance parameter, e.g.

https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L33

**Comment by xsasx** [comment]
mhhhh i mean extrusion steps - so i messure my filament- extrude 10*10 got 21mm left and than ? sorry im not sooooo familiar with all these things

**Comment by theopensourcerer** [comment]
There are lots of "howtos" online about how to do this:

https://mattshub.com/2017/04/19/extruder-calibration/

I am not sure what else you really need to know... The extruder configuration is also in the same example file:

https://github.com/KevinOConnor/klipper/blob/master/config/example.cfg#L94

**Comment by xsasx** [comment]
If  i want to sen M503 it says command does not exist - thats my problem - if i follow one of these how tos it wont work with klipper that way :/ so i want to know how i can calibrate my esteps under klipper

**Comment by theopensourcerer** [comment]
Why do you need to send M503? There is no "EEPROM" in klipper. Current settings are in your printer.cfg file.

**Comment by ikarisan** [comment]
M503 is not needed to calibrate the steps. You will find your current values (step_distance:) inside the printer.cfg file.

**Comment by gdkinney** [comment]
Most online tutorials are assuming step/mm (used by Marlin and others) instead of mm/step used by Klipper. You need to invert the measured/expected ratio, in this case it's (90/100)*0.0105=0.00945 .

**Comment by ikarisan** [comment]
@xsasx I would calc it like this:

1) Mark you filament 120mm above the entry to your extruder.
2) Heat up the nozzle to your desired printing temperature
3) Home all axis to get in "printer ready" state
4) Lift up your nozzle by 50mm (to make room for the filament!)
5) Execute the following command (one by one)
  5a) G92 E0
  5b) G1 E100 F100
6) Measure the distance between your extruder entry and the mark on your filament.

I.e if it is 28mm instead of 20mm (120mm - 100mm) than you are UNDERextruding by 8mm ==> 92mm instead of 100mm.

Now calc:

c := current value in configuration.cfg
m := measured left over filament
d := desired mm
n := new value for configuration.cfg

((120 - m) / d) * c = n
((120 - 28) / 100) * 0.010500 = 0,009660
(92 / 100) * 0.010500 = 0,009660

As you can see, for underextrusion the new value is lower than the old one. 
You may play around with the last two numbers to fine tune.

**Comment by KevinOConnor** [comment]
It looks like the original question was answered, so I'm going to close this issue.

-Kevin

**Comment by Ianmcmill** [comment]
I still don't get it why Klipper switches the whole quasi standard of steps/mm into mm/steps. But then again I am free to use Klipper or let it be. Am I right ;)

**Comment by KevinOConnor** [comment]
FYI, it's done that way to use consistent measurement units in the config file - mm for distance, amps for current, volts for voltage, seconds for time, ohms for resistance, etc.  I know it's different from other firmware, but it's just weird to configure this one parameter in units of inverse millimeters.

-Kevin

**Comment by dotps1** [comment]
i agree with the consistency, I put a note in my config file so I don't forget:

```
# Measure 120mm, then extrude 100mm
# G1 E100 F100
# step_distance = old_e_steps * ((120 - distance_to_mark) / 100)
```

**Comment by NameOfTheDragon** [comment]
> @xsasx I would calc it like this:
> 
> 1. Mark you filament 120mm above the entry to your extruder.
> 2. Heat up the nozzle to your desired printing temperature
> 3. Home all axis to get in "printer ready" state
> 4. Lift up your nozzle by 50mm (to make room for the filament!)
> 5. Execute the following commands (one by one)
>    5a) G92 E0
>    This resets the "extruded material" value to 0.
>    5b) G1 E100 F100
>    This extrudes 100mm filament with 100mm/min.
> 6. Now measure the distance between your extruder entry and the mark on your filament.
> 
> I.e if it is 28mm instead of 20mm (120mm - 100mm) than you are UNDERextruding by 8mm ==> 92mm instead of 100mm. If it shows 15mm than your are OVERextruding by 5mm ==> 105mm.
> 
> Now calc:
> 
> c := current value in configuration.cfg
> m := measured left over filament
> d := desired mm
> n := new value for configuration.cfg
> 
> ((120 - m) / d) * c = n
> ((120 - 28) / 100) * 0.010500 = 0,009660
> (92 / 100) * 0.010500 = 0,009660
> 
> As you can see, for underextrusion the new value is lower than the old one.
> You may play around with the last two numbers to fine tune.

It would be absolutely awesome for people new to Klipper if this appeared in the "getting started" document. It is quite a culture shock coming from Marlin and this would be a great help, in my opinion.

**Comment by Hairyloon** [comment]
My Pi broke, so I've had to reinstall and I see that we've moved from steps/mm, which was simple and easy to fathom, to microsteps and rotation distance, which appears to be based on guesswork...

> If unsure, set microsteps: 16 in the config and use 16 in the formula above.

I can imagine that maybe this makes it easier to programme since the calculations have to be done by the user rather than the software, and maybe there are some additional instructions that I've missed: perhaps a command to move (n) microsteps, so we can see how far it goes, but otherwise it seems to make no sense...

**Comment by manyhats-mike** [comment]
Yeah, it wasn't obvious about the transition from step_distance to rotation_distance and this is the #1 google hit.  A bit of digging, I'm hoping I can follow this guide for anyone else that lands here first:
https://github.com/KevinOConnor/klipper/blob/master/docs/Rotation_Distance.md
