### ISSUE TITLE
AM437X series processor support

### ISSUE THREAD

**Issue by npgoalkeeper** [KevinOConnor/klipper#969]
What would it take additionally to add support for the AM437X series processors from Texas Instruments, specifically the AM4379 processor for real-time operations?

**Comment by KevinOConnor** [comment]
The AM437X chips appear to be very similar to the cpu in the Beaglebone.  So, I suppose one could install Linux on them and port the Klipper PRU code so that it operates similarly to the Beaglebone.  That said, generally any type of port takes a lot of work and it's very hard to say what would be necessary.

-Kevin

**Comment by npgoalkeeper** [comment]
Thanks!
